- kernel/errors.ml
- kernel/reduction.ml
- kernel/signature.ml
- kernel/signature.mli
- tests/KO/guard1.dk
- tests/KO/guard2.dk
- tests/OK/guard1.dk
- tests/OK/guard2.dk
- tests/OK/guard3.dk
This pull request (partially) resolve the issue #23
> No more fatal error, but no adress (line 0,column 0) printed

- .travis.yml
- tests/external_tests.sh
As proposed yesterday, I suppressed the file taking too much time in the matita library and do the checking on 3 libraries.
> Perform continuous integration on 3 libraries of Dedukti

- kernel/signature.ml
> Replace some assertions by an error or by an import.

- kernel/confluence.ml
- kernel/env.ml
- kernel/errors.ml
- kernel/pp.ml
- kernel/rule.ml
- kernel/rule.mli
- kernel/signature.mli
> Using untyped rule instead of typed rules in signature.

- api/env.ml
- api/env.mli
- commands/dkcheck.ml
- commands/dkdep.ml
- kernel/basic.ml
- kernel/basic.mli
- kernel/confluence.ml
- kernel/confluence.mli
- kernel/dtree.ml
- kernel/dtree.mli
- kernel/reduction.ml
- kernel/reduction.mli
- kernel/signature.ml
- kernel/signature.mli
- kernel/typing.ml
- kernel/typing.mli
- parser/menhir_parser.mly
- parser/scoping.ml
The Debug module now includes an extensible type, allowing application which uses Dedukti as a library to add there flags.
> Refactoring debug

- .travis.yml
- GNUmakefile
Travis offers such an option called "cron jobs". Is it useful?
> Add monthly build of Dedukti with full tests

- kernel/dtree.ml
- kernel/dtree.mli
- kernel/reduction.ml
I do not know what I'm doing, but @Gaspi told me it was a good idea, and I kind of trust him.
Reverts Deducteam/Dedukti#138
> Revert "Revert "[WIP] Removing Syntactic/MP distinctions""

- kernel/signature.ml
- kernel/signature.mli
A simple extension of the API.
> Add a way to get a function definition

- api/env.ml
- api/env.mli
- api/errors.ml
- commands/dkcheck.ml
- kernel/reduction.ml
- kernel/reduction.mli
- kernel/typing.ml
- tests/OK/eta_0.dk
- tests/OK/eta_0b.dk
- tests/OK/eta_1.dk
- tests/OK/eta_2.dk
- tests/OK/eta_2b.dk
Implementation of a "-eta" flag enabling eta expansions in the conversion test.
> Flag to allow eta in conversion test

- parser/menhir_parser.mly
- tests/OK/let_syntax.dk
> Implementing "lets" as syntactic sugar

- api/env.ml
- api/errors.ml
- kernel/basic.ml
- kernel/reduction.ml
- kernel/reduction.mli
- kernel/rule.ml
- kernel/rule.mli
- kernel/signature.ml
- kernel/signature.mli
- kernel/typing.ml
- kernel/typing.mli
Part of #125 . This PR isolates modifications done to the kernel.
> Functorize the rewrite engine of Dedukti (only modifications to the kernel)

- .travis.yml
Lets see if it breaks something...
> Test also OCaml 4.08 and 4.09

- kernel/signature.ml
- kernel/signature.mli
- parsing/menhir_parser.mly
Is this the same as #204 for you @francoisthire ?
> optimization for thousands of rules added one by one

- parsing/menhir_parser.mly
Simplifies Dedukti's syntax.
As suggested in team meeting.
> Syntax fix.

- GNUmakefile
- api/meta.ml
- api/meta.mli
- api/processor.ml
- api/processor.mli
- commands/dkmeta.ml
- commands/dune
We add dkmeta in this repository to ease the development and releasing tools.
> Add dkmeta in the repository

- Makefile
- api/errors.ml
- api/errors.mli
- api/processor.ml
- commands/dkmeta.ml
- tests/meta/beta.dk
- tests/meta/beta.output
- tests/meta/beta_2.dk
- tests/meta/beta_2.output
- tests/meta/simple.dk
- tests/meta/simple.output
- tests/meta/simple_2.dk
- tests/meta/simple_2.output
- tests/scripts/KO.sh
- tests/scripts/META.sh
- tests/scripts/OK.sh
- tests/tests
- tests/tests.sh
An experiment that adds a simple integration test framework for dkmeta.
> Dkmeta: Prototype the integration test framework

- .github/workflows/main.yml
- api/meta.ml
- api/meta.mli
- universo/commands/universo.ml
- universo/common/constraints.ml
- universo/solving/solver.ml
The last tweaks to `dkmeta` broke `universo` compilation.
> Make universo compiles again

- .github/workflows/main.yml
- .ocamlformat
- Makefile
- api/dep.ml
- api/dep_legacy.ml
- api/pp.ml
- api/processor.ml
- parsing/dune
- parsing/entry.ml
- parsing/entry.mli
- parsing/lexer.mll
- parsing/menhir_parser.mly
- parsing/tokens.ml
- tests/KO/opacity.dk
- tests/KO/opacity2.dk
- tests/KO/opaque_a.dk
- tests/KO/pragma.dk
- tests/KO/pragma2.dk
- tests/LIB/prv.dk
- tests/OK/pragma.dk
- tests/OK/underscore1.dk
- tests/main.ml
This PR aims to be consistent with the new standard defined https://github.com/Deducteam/Dedukti-standard
> Implement Dedukti standard

- commands/dkdep.ml
Maybe we should consider add a regression test?
> Dkdep: Make error message consistent

- .github/dependabot.yml
- .github/workflows/main.yml
- .ocamlformat
- dedukti.opam
- dune-project
- universo.opam
- add dependabot.yml
- upgrade github action versions
- test other ocaml versions
- do not check formatting anymore (ocamlformat.0.24.1 is not compatible with ocaml.5.2.0)
- update dune-project and generated opam files
> ci: upgrade script + test various ocaml versions
