kernel/dtree.ml
kernel/dtree.mli
kernel/reduction.ml

Add names in the dtree type so that it is easier to check which rule is applied. This is the first step toward a command to print rewriting steps while checking a term.

Add the name of the rule for the dtree type

---

commands/dkcheck.ml
kernel/basic.ml
kernel/basic.mli
kernel/matching.ml
kernel/pp.ml
kernel/term.ml
kernel/typing.ml
parser/lexer.mll
parser/menhir_parser.mly

Try to solve issue #40 . However, I did not extend the grammar for lambdas in patterns. Indeed, on the following example there would be a conflict :
```
#NAME subst.
A : Type.
def T : (A -> A) -> Type.
[] T (_ => _) --> A.
#EVAL T (x => x). (; What should be the answer here ? ;)
```

Allows identifiers to start with a `?` or a `!` and solved issue #40

---

kernel/term.ml
kernel/term.mli
kernel/typing.ml

Renaming DB variables before ConvertibilityError

---

kernel/basic.ml
kernel/basic.mli
kernel/reduction.ml

When checking for the convertibility of two apps, recursively check for head convertibility first.
Also rely on exception to handle non convertibility rather than option types.

Checking convertibility head first.

---

api/env.ml
tests/KO/arrowCodomainType.dk
tests/KO/arrowDomainType.dk
tests/KO/arrowDomainType2.dk
tests/KO/kind_typable_2.dk
tests/KO/typeArrowType.dk
tests/OK/inferingKindForArrowWithCodomainType.dk
tests/OK/inferingKindForType.dk

Hi all,
I wanted to fix the issue raised in #150 so I had a quick look at it. And as everybody probably guessed, the problem came from the fact that in env.ml, in order to infer the type of a term `t`, we call `Typing.infer` on `t` and obtain its type `ty`, and just after that we also check that the produced type `ty` is itself typable. That makes sense according to the LF typing rules, but only if the type obtained `ty` is not `Kind`, because `Kind` does not have a type itself (that's the end of the hierarchy in LF!), but that should not prevent `Type` to have type `Kind`.
So now, in Env.infer, we call Typing.infer, and **only if the result is not `Kind`** we infer a type for it as well (that we immediately throw away, as before).
The same thing had to be done in the (safe) reduction …

Make #INFER Type produce KIND

---

kernel/rule.mli
kernel/typing.ml
kernel/typing.mli

It is required for external usage to have a way from a signature and a rule_infos to get the typed environment inferred.

Rule_infos_to_typed_rule in typing.ml

---

api/errors.ml
kernel/signature.ml
kernel/signature.mli

This PR remove the useless function `read_dko` and replace it by a function `access_signature` which gives the user access to the content of the signature given in argument.

Export the signature

---

kernel/rule.ml
kernel/signature.ml
kernel/signature.mli

Lazily adding new rules into signature without computing decision tree.
Decision tree is computed on demand, whenever it is required.

Lazy rule addition into signature

---

kernel/typing.ml
kernel/typing.mli

Fraçois did not like to have in the API the function `typed_rule_of_rule_infos`since it was the composition of a function `untyped_rule_of_rule_infos`which was not accessible since inlined with `check_rule` which is in the API.
This PR separates the really new feature in the ad-hoc composition.

More elementary function in the APi

---

README.md
api/env.ml
api/env.mli
api/errors.ml
commands/dkcheck.ml
tests/KO/nonleftlinear.dk

Adds a new `--ll` flag to `dkcheck` checking that all rules are left-linear.
It's a property people usually want and it's nice to be able to check it, especially on generated files where the rewrite rules are huge and unreadable.
I believe there should even be more of these "disable advanced features" flags such as:
- "no brackets" to keep an efficient system.
- "no rewrite" to make sure no rewrite rule is added. This still allows for opaque definitions: `thm`. Probably useful in files supposed to only provided proofs and not extend the system.
- "no command"
- ...
but this is open for discussion.
These checks are not very useful but not very hard to implement either.

Flag to forbid non-left-linear rules

---

api/env.ml
api/processor.ml
commands/dkcheck.ml
commands/dkprune.ml
kernel/basic.ml
kernel/basic.mli
kernel/confluence.ml
kernel/confluence.mli
kernel/dtree.ml
kernel/dtree.mli
kernel/matching.ml
kernel/matching.mli
kernel/reduction.ml
kernel/reduction.mli
kernel/signature.ml
kernel/signature.mli
kernel/typing.ml
kernel/typing.mli
parsing/scoping.ml

New implementation of debug flag as references. This allows to retrieve a flag's current value by directly dereferencing it, sparing a systematic hash computation.
This should reduce diff of #203

Implementation of debug flags as references

---

api/env.ml
api/env.mli
api/errors.ml
commands/dktop.ml
kernel/basic.ml
kernel/basic.mli
kernel/confluence.ml
kernel/confluence.mli
kernel/dtree.ml
kernel/dtree.mli
kernel/reduction.ml
kernel/rule.ml
kernel/rule.mli
kernel/signature.ml
kernel/signature.mli
kernel/typing.ml
kernel/typing.mli

This is in accordance with the [OCaml Programming Guidelines](https://ocaml.org/learn/tutorials/guidelines.html#Separate-words-by-underscores-int-of-string-not-intOfString)
It should help reduce the diff of #190 .

Fixed exception naming

---

kernel/matching.ml
kernel/matching.mli
kernel/reduction.ml

When a non-linear constraint is solved as an equation in
`matching.ml` we call the `R.constraint_convertibility` function
instead of `R.are_convertible`.

matching: Fix the API issue and call the correct function

---

.travis.yml
README.md
dune-project

Dedukti is released under the CeCILL-B license (as said in the README
and the LICENSE file). This commit fixes the license declaration in
the dune-project file so that the generated dedukti.opam file declares
the correct license.

dune-project: Fix the license declaration.

---

commands/dkcheck.ml
commands/dkmeta.ml
commands/dune
tests/dedukti.ml
tests/scripts/KO.sh
tests/scripts/OK.sh
tests/tezt/_regressions/tests/OK/nsteps3.dk_dkcheck_ok.out
tests/tezt/_regressions/tests/meta/simple.dk_dkmeta.out
tests/tezt/_regressions/tests/meta/simple.dk_dkmeta_no_meta.out

Use [cmdliner](https://erratique.ch/software/cmdliner/doc/Cmdliner) to provide a unique command for all tools
Todo:
**Warning:** the option `-nc` is no longer available. It is replaced by `--nc` or `--no-colors`

cmdliner for dkcheck

---

.github/workflows/main.yml
Makefile
libraries/dedukti-libraries.sh
libraries/dklib.sh
libraries/focalide.sh
libraries/holide.sh
libraries/iprover.sh
libraries/matita-light.sh
libraries/matita.sh
libraries/verine.sh
libraries/zenon_modulo.sh

This pull request tries to get back some CI running on the libraries.
I am not familiar with `nubo` yet, but it is probably better to use it rather than get old archives and sedding them to update the syntax.
By the time, I think that checking libraries remains useful.

Fixing the commands to compile libraries and add Cron job to the CI

---

kernel/reduction.ml

Partial answer to #279 .
1. We add a physical equality for optimisation. We can check this may be triggered by some unit tests
2. We still keep the syntactic equality. This is to avoid to compute the WHNF while to terms are syntactically equal (see test : `tests/OK/sharing.dk`).

Kernel: Optimise conversion

---

dedukti.opam
dune-project
universo.opam

- universo depends on dedukti >= 2.7
- It is advised to use dune >= 2.7 to generate opam files (see linter
of opam ci)
- z3 >= 4.8.11 (a lower bound may exist)

Miscellaneous fixes

---

CONTRIBUTING.md
commands/dkcheck.ml
commands/main.ml
tests/dedukti.ml
tests/dedukti.mli

The command line manual via `--help`, refers to command `dkcheck` instead of `dk`. This PR fixes this issue in the command line manual (#286) and in some of the comments in the code.

Update command line manual

---

commands/dkcheck.ml
commands/dkdep.ml
commands/dkmeta.ml
commands/dkpretty.ml
commands/dkprune.ml
commands/dktop.ml
commands/dune
commands/main.ml
misc/gen_version.ml

This PR fixes the display of Dedukti version (#300) when called in command line (for instance dk --version)

Fix display of version
